<header class="navbar navbar-dark sticky-top bg-dark flex-md-nowrap p-0 shadow">
    <a class="navbar-brand col-md-3 col-lg-2 me-0 px-3" href="#"><?php echo $_SESSION['usuario'][0]['nombre'] ?></a>
    <button class="navbar-toggler position-absolute d-md-none collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#sidebarMenu" aria-controls="sidebarMenu" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <!-- <input class="form-control form-control-dark w-100 hidden" type="text" placeholder="Search" aria-label="Search"> -->
    <ul class="navbar-nav form-control form-control-dark px-3">
        <li class="nav-item text-nowrap">
            <a class="nav-link" href="login.php?exit=true">Sign out</a>
        </li>
    </ul>
</header>


<div class="row">
    <nav id="sidebarMenu" class="col-md-3 col-lg-2 d-md-block bg-light sidebar collapse">
        <div class="position-sticky pt-3">
            <ul class="nav flex-column">
                <li class="nav-item">
                    <a class="nav-link d-flex align-items-center" aria-current="page" href="caja.php">
                        <span data-feather="home"></span>
                        <span class="material-icons">
                            store
                        </span>
                        Caja
                    </a>
                </li>
                <li>
                    <a class="nav-link d-flex align-items-center" href="reportes.php?user=todos&fecha=todas">
                        <span class="material-icons">
                            table_view
                        </span>
                        Reportes
                    </a>
                </li>
                <li class="nav-item ">
                    <a class="nav-link d-flex align-items-center" href="inventario.php">
                        <span data-feather="file"></span>
                        <span class="material-icons">
                            inventory
                        </span>
                        Inventario
                    </a>
                </li>
                <li class="nav-item ">
                    <a class="nav-link d-flex align-items-center" href="alertas.php">
                        <span data-feather="shopping-cart"></span>
                        <span class="material-icons">
                            warning
                        </span>
                        Alertas
                    </a>
                </li>
                <?php if ($_SESSION['usuario'][0]['id_cargo'] == 1 || $_SESSION['usuario'][0]['id_cargo'] == 3) { ?>
                    <li class="nav-item ">
                        <a class="nav-link d-flex align-items-center" href="productos.php">
                            <span data-feather="users"></span>
                            <span class="material-icons">
                                settings
                            </span>
                            Administracion
                        </a>
                    </li>
                <?php } ?>
                <li class="nav-item ">
                    <a class="nav-link d-flex align-items-center" href="facturas.php">
                        <span data-feather="users"></span>
                        <span class="material-icons">
                            receipt_long
                        </span>
                        Facturas
                    </a>
                </li>
            </ul>

            <!-- <h6 class="sidebar-heading d-flex justify-content-between align-items-center px-3 mt-4 mb-1 text-muted">
                <span>Saved reports</span>
                <a class="link-secondary" href="#" aria-label="Add a new report">
                    <span data-feather="plus-circle"></span>
                </a>
            </h6>
            <ul class="nav flex-column mb-2">
                <li class="nav-item">
                    <a class="nav-link" href="#">
                        <span data-feather="file-text"></span>
                        Current month
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">
                        <span data-feather="file-text"></span>
                        Last quarter
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">
                        <span data-feather="file-text"></span>
                        Social engagement
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">
                        <span data-feather="file-text"></span>
                        Year-end sale
                    </a>
                </li> -->
            </ul>
        </div>
    </nav>
</div>